services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/project
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: database
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lig/mysql
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: stockpress

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - php
      - database
      - nginx
